# Generated by Django 2.1.7 on 2020-08-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_db_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project',
            name='other_user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
