# Generated by Django 2.1.7 on 2020-09-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20200913_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_apis',
            name='last_api_body',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='db_apis',
            name='last_body_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
